# Generated by Django 5.0.4 on 2024-07-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='memory',
            field=models.PositiveIntegerField(help_text='Memory in GB'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.PositiveIntegerField(help_text='Storage in GB'),
        ),
    ]
