# Generated by Django 5.0.4 on 2024-08-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_tennisplayer_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tennisplayer',
            managers=[
            ],
        ),
    ]
