# Generated by Django 5.0.4 on 2024-07-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_driver_drivinglicence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivinglicence',
            old_name='licence_number',
            new_name='license_number',
        ),
        migrations.AlterField(
            model_name='drivinglicence',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='main_app.driver'),
        ),
    ]
