# Generated by Django 5.0.4 on 2024-07-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_licence_number_drivinglicence_license_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrivingLicence',
            new_name='DrivingLicense',
        ),
    ]
