# Generated by Django 5.0.4 on 2024-06-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
