# Generated by Django 5.0.4 on 2024-06-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product_created_on_product_last_edited_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_edited_on',
        ),
    ]
