# Generated by Django 5.0.4 on 2024-07-10 10:07

from django.db import migrations, models
import django.db.models.deletion
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_subject_student_subjects'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subject')),
            ],
        ),
        migrations.AlterModelTable(
            name='studentenrollment',
            table='main_app_student_subjects',
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(through='main_app.StudentEnrollment', to='main_app.Subject'),
        ),
    ]

    # Next, in the operations list, we add a specialized operation called SeparateDatabaseAndState which allows us to alter the state and the database separately. In this specialized operation, we will add the above-written state operations.
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),

        # We need to add the additional fields from the StudentEnrollment model: "entrollment_date" and "grade".
        migrations.AddField(
            model_name='StudentEnrollment',
            name='enrollment_date',
            field=models.DateField(default=date.today),
        ),
        migrations.AddField(
            model_name='StudentEnrollment',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')],
                                   max_length=1, null=True),
        ),

        # Finally, we reset the name (which is set to main_app_student_subjects above) to use the default naming convention
        migrations.AlterModelTable(
            name='studentenrollment',
            table=None,
        ),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='StudentEnrollment',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('enrollment_date', models.DateField(default=date.today)),
    #             ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
    #             ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
    #             ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subject')),
    #         ],
    #     ),
    #     migrations.AlterField(
    #         model_name='student',
    #         name='subjects',
    #         field=models.ManyToManyField(through='main_app.StudentEnrollment', to='main_app.subject'),
    #     ),
    # ]
