# Generated by Django 5.0.4 on 2024-08-03 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name of the astronaut', max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('phone_number', models.CharField(help_text='Phone number of the astronaut', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits.', regex='^\\d+$')])),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the astronaut is currently active')),
                ('date_of_birth', models.DateField(blank=True, help_text='Birth date of the astronaut', null=True)),
                ('spacewalks', models.IntegerField(default=0, help_text='Number of spacewalks the astronaut has participated in', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the spacecraft', max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('manufacturer', models.CharField(help_text='Manufacturer of the spacecraft', max_length=100)),
                ('capacity', models.PositiveSmallIntegerField(help_text='Number of astronauts the spacecraft can carry', validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.FloatField(help_text='Weight of the spacecraft in kilograms', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('launch_date', models.DateField(help_text='Launch date of the spacecraft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the mission', max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True, help_text='Detailed description of the mission', null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Planned', help_text='Status of the mission', max_length=9)),
                ('launch_date', models.DateField(help_text='Launch date of the mission')),
                ('astronauts', models.ManyToManyField(help_text='Astronauts participating in the mission', related_name='missions', to='main_app.astronaut')),
                ('commander', models.ForeignKey(blank=True, help_text='Commander of the mission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_missions', to='main_app.astronaut')),
                ('spacecraft', models.ForeignKey(help_text='Spacecraft associated with the mission', on_delete=django.db.models.deletion.CASCADE, to='main_app.spacecraft')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
